name = "cloudflare-pages"
compatibility_date = "2024-12-27"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[vars]
VITE_API_URL = "http://localhost:5173" 

[env.preview.vars]
VITE_API_URL = "https://maverick-public-services-stage.dev.gotickets.com" 
VITE_MAVERICK_URL="https://maverick-public-services-stage.dev.gotickets.com"

[env.production.vars]
VITE_API_URL = "https://fluffy-couscous-53f.pages.dev" 
VITE_MAVERICK_URL="https://maverick-public-services-stage.dev.gotickets.com"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"