name = "cloudflare-pages"
compatibility_date = "2024-12-27"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[vars]
VITE_MAVERICK_URL="https://maverick-public-services-stage.dev.gotickets.com"
NODE_ENV="development"
VITE_APP_ENV="development"
VITE_GB_CLIENT_KEY="sdk-nBR0cXqdj9rICERK"

[env.preview.vars]
VITE_MAVERICK_URL="https://maverick-public-services-stage.dev.gotickets.com"
VITE_APP_ENV="preview"
VITE_GB_CLIENT_KEY="sdk-nBR0cXqdj9rICERK"

# this is staging environment
[env.production.vars]
VITE_MAVERICK_URL="https://maverick-public-services-stage.dev.gotickets.com"
VITE_APP_ENV="production"
VITE_GB_CLIENT_KEY="sdk-Qfu8RXU7YapBe0HF"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"