export const performerIdOnly = {
  adGroupEntityResult: {
    performer: {
      id: 3133,
      name: 'Orlando Magic',
      primaryCategoryId: 175,
      parking: false,
      slug: 'orlando-magic-tickets',
      heroImagePath:
        'https://static.gotickets.com/693731dd-f58d-40aa-ae7d-a1be498fae73.webp',
      primaryCategory: {
        id: 175,
        name: 'NBA Basketball',
        eventType: 'SPORTS',
        slug: 'nba-basketball',
      },
      cmsPageId: 162,
    },
  },
  events: [
    {
      id: 463736,
      name: 'NBA Preseason - Orlando Magic at New Orleans Pelicans',
      venueId: 1718,
      venueConfigurationId: 5769,
      eventTimeLocal: '2024-10-07T13:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-07T18:30:00',
      eventPerformers: [
        {
          id: 533784,
          performerId: 3133,
          master: false,
          performer: {
            id: 3133,
            name: 'Orlando Magic',
            primaryCategoryId: 175,
            parking: false,
            slug: 'orlando-magic-tickets',
            primaryCategory: {
              id: 175,
              name: 'NBA Basketball',
              eventType: 'SPORTS',
            },
            cmsPageId: 162,
          },
        },
      ],
      venue: {
        id: 1718,
        name: 'Smoothie King Center',
        city: 'New Orleans',
        state: 'LA',
        postalCode: '70113',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 5,
        slug: 'smoothie-king-center',
        heroImagePath:
          'https://static.gotickets.com/6650e7fe-7522-4554-84f7-071c6bcadef8.webp',
        singleLineAddress: 'New Orleans, LA 70113',
      },
      venueConfiguration: {
        name: 'NBA: Basketball',
        svgMapFileName: '510355fa-cf88-4668-bb9a-5c315d1a0b04',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 463732,
      name: 'NBA Preseason - Orlando Magic at San Antonio Spurs',
      venueId: 2644,
      venueConfigurationId: 2225,
      eventTimeLocal: '2024-10-09T20:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-10T01:00:00',
      eventPerformers: [
        {
          id: 533776,
          performerId: 3133,
          master: false,
          performer: {
            id: 3133,
            name: 'Orlando Magic',
            primaryCategoryId: 175,
            parking: false,
            slug: 'orlando-magic-tickets',
            primaryCategory: {
              id: 175,
              name: 'NBA Basketball',
              eventType: 'SPORTS',
            },
            cmsPageId: 162,
          },
        },
      ],
      venue: {
        id: 2644,
        name: 'Frost Bank Center (Formerly AT&T Center)',
        city: 'San Antonio',
        state: 'TX',
        postalCode: '78219',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 76,
        slug: 'frost-bank-center-formerly-att-center',
        heroImagePath:
          'https://static.gotickets.com/df1f76d1-a820-4e43-9f94-9c68d7efe4e6.webp',
        singleLineAddress: 'San Antonio, TX 78219',
      },
      venueConfiguration: {
        name: 'NBA Basketball',
        svgMapFileName: '106f74c5-0365-4e32-bf07-aa0c46f8cc11',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 458774,
      name: 'NBA Preseason - New Orleans Pelicans at Orlando Magic',
      venueId: 161,
      venueConfigurationId: 3087,
      eventTimeLocal: '2024-10-11T19:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 463342,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-11T23:00:00',
      eventPerformers: [
        {
          id: 528334,
          performerId: 3133,
          master: true,
          performer: {
            id: 3133,
            name: 'Orlando Magic',
            primaryCategoryId: 175,
            parking: false,
            slug: 'orlando-magic-tickets',
            primaryCategory: {
              id: 175,
              name: 'NBA Basketball',
              eventType: 'SPORTS',
            },
            cmsPageId: 162,
          },
        },
      ],
      venue: {
        id: 161,
        name: 'Kia Center (Formerly Amway Center)',
        city: 'Orlando',
        state: 'FL',
        postalCode: '32801',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 16,
        slug: 'kia-center-formerly-amway-center',
        heroImagePath:
          'https://static.gotickets.com/9bb520cd-f642-4f01-ada2-df5fdbbcbd1f.webp',
        singleLineAddress: 'Orlando, FL 32801',
      },
      venueConfiguration: {
        name: 'Basketball (Orlando Magic) ',
        svgMapFileName: 'aa3b7358-cdea-4dce-95a4-5695b6e4c499',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 458775,
      name: 'NBA Preseason - Philadelphia 76ers at Orlando Magic',
      venueId: 161,
      venueConfigurationId: 3087,
      eventTimeLocal: '2024-10-18T19:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 463343,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-18T23:00:00',
      eventPerformers: [
        {
          id: 528337,
          performerId: 3133,
          master: true,
          performer: {
            id: 3133,
            name: 'Orlando Magic',
            primaryCategoryId: 175,
            parking: false,
            slug: 'orlando-magic-tickets',
            primaryCategory: {
              id: 175,
              name: 'NBA Basketball',
              eventType: 'SPORTS',
            },
            cmsPageId: 162,
          },
        },
      ],
      venue: {
        id: 161,
        name: 'Kia Center (Formerly Amway Center)',
        city: 'Orlando',
        state: 'FL',
        postalCode: '32801',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 16,
        slug: 'kia-center-formerly-amway-center',
        heroImagePath:
          'https://static.gotickets.com/9bb520cd-f642-4f01-ada2-df5fdbbcbd1f.webp',
        singleLineAddress: 'Orlando, FL 32801',
      },
      venueConfiguration: {
        name: 'Basketball (Orlando Magic) ',
        svgMapFileName: 'aa3b7358-cdea-4dce-95a4-5695b6e4c499',
        generalAdmission: false,
        staticMap: false,
      },
    },
  ],
}

export const performerIdAndRegionId = {
  adGroupEntityResult: {
    performer: {
      id: 7821,
      name: '21 Savage',
      primaryCategoryId: 145,
      parking: false,
      slug: '21-savage-tickets',
      heroImagePath:
        'https://static.gotickets.com/b4225d3a-e46b-4925-9fd8-bb4f9f1a7de6.webp',
      primaryCategory: {
        id: 145,
        name: 'Rap/Hip Hop',
        eventType: 'CONCERTS',
        slug: 'rap-hip-hop',
      },
      cmsPageId: 585,
    },
    region: {
      id: 75,
      name: 'Albuquerque',
      venueRadius: 0,
      heroImagePath: 'a8b5a22a-2b99-45fc-b83c-d8596784f080.webp',
      slug: 'albuquerque-events',
    },
  },
  events: [
    {
      id: 463736,
      name: 'NBA Preseason - Orlando Magic at New Orleans Pelicans',
      venueId: 1718,
      venueConfigurationId: 5769,
      eventTimeLocal: '2024-10-07T13:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-07T18:30:00',
      eventPerformers: [
        {
          id: 533784,
          performerId: 7821,
          master: false,
          performer: {
            id: 3133,
            name: 'Orlando Magic',
            primaryCategoryId: 175,
            parking: false,
            slug: 'orlando-magic-tickets',
            primaryCategory: {
              id: 175,
              name: 'NBA Basketball',
              eventType: 'SPORTS',
            },
            cmsPageId: 162,
          },
        },
      ],
      venue: {
        id: 1718,
        name: 'Smoothie King Center',
        city: 'New Orleans',
        state: 'LA',
        postalCode: '70113',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 75,
        slug: 'smoothie-king-center',
        heroImagePath:
          'https://static.gotickets.com/6650e7fe-7522-4554-84f7-071c6bcadef8.webp',
        singleLineAddress: 'New Orleans, LA 70113',
      },
      venueConfiguration: {
        name: 'NBA: Basketball',
        svgMapFileName: '510355fa-cf88-4668-bb9a-5c315d1a0b04',
        generalAdmission: false,
        staticMap: false,
      },
    },
  ],
}

export const performerIdAndVenueId = {
  adGroupEntityResult: {
    performer: {
      id: 11571,
      name: 'Kid Cudi',
      primaryCategoryId: 145,
      parking: false,
      slug: 'kid-cudi-tickets',
      heroImagePath:
        'https://static.gotickets.com/f3deff4f-9982-412b-a5c6-4d26ad0dfefd.webp',
      primaryCategory: {
        id: 145,
        name: 'Rap/Hip Hop',
        eventType: 'CONCERTS',
        slug: 'rap-hip-hop',
      },
      cmsPageId: 581,
    },
    venue: {
      id: 2288,
      name: 'Wells Fargo Center - PA',
      parentVenue: false,
      parking: false,
      slug: 'wells-fargo-center-pa',
      heroImagePath:
        'https://static.gotickets.com/99ec9958-2d0a-43f3-af81-60b863fe2fdd.webp',
      singleLineAddress: '',
    },
    region: {
      id: 8,
      name: 'Philadelphia',
      venueRadius: 0,
      heroImagePath: '23bad46b-564a-4e25-a90a-00d27f072a5b.webp',
      slug: 'philadelphia-events',
    },
  },
  events: [
    {
      id: 273870,
      name: 'Kacey Musgraves',
      venueId: 368,
      venueConfigurationId: 24822,
      eventTimeLocal: '2024-09-04T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 285148,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-04T23:30:00',
      eventPerformers: [
        {
          id: 324819,
          performerId: 11571,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 2288,
        name: 'Bryce Jordan Center',
        city: 'State College',
        state: 'PA',
        postalCode: '16801',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 7,
        slug: 'bryce-jordan-center',
        singleLineAddress: 'State College, PA 16801',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'e8fe47a6-82bb-4f19-80d2-45116e7d0ec9',
        generalAdmission: false,
        staticMap: false,
      },
    },
  ],
}

export const performerIdAndVenueIdAndRegionId = {
  adGroupEntityResult: {
    performer: {
      id: 5981,
      name: 'Kacey Musgraves',
      primaryCategoryId: 138,
      parking: false,
      slug: 'kacey-musgraves-tickets',
      heroImagePath:
        'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
      primaryCategory: {
        id: 138,
        name: 'Country and Folk',
        eventType: 'CONCERTS',
        slug: 'country-and-folk',
      },
      cmsPageId: 591,
    },
    venue: {
      id: 1815,
      name: 'TD Garden',
      parentVenue: false,
      parking: false,
      slug: 'td-garden',
      heroImagePath:
        'https://static.gotickets.com/a71b4f62-05b5-428c-93c2-9d84b0306e8c.webp',
      singleLineAddress: '',
    },
    region: {
      id: 19,
      name: 'Boston',
      venueRadius: 0,
      heroImagePath: '0a9c1976-42c4-480f-a70f-b679e0358cd6.webp',
      slug: 'boston-events',
    },
  },
  events: [
    {
      id: 273870,
      name: 'Kacey Musgraves',
      venueId: 368,
      venueConfigurationId: 24822,
      eventTimeLocal: '2024-09-04T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 285148,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-04T23:30:00',
      eventPerformers: [
        {
          id: 324819,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 368,
        name: 'Bryce Jordan Center',
        city: 'State College',
        state: 'PA',
        postalCode: '16801',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 7,
        slug: 'bryce-jordan-center',
        singleLineAddress: 'State College, PA 16801',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'e8fe47a6-82bb-4f19-80d2-45116e7d0ec9',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273873,
      name: 'Kacey Musgraves',
      venueId: 1815,
      venueConfigurationId: 24823,
      eventTimeLocal: '2024-09-06T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 278207,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-06T23:30:00',
      eventPerformers: [
        {
          id: 324822,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1815,
        name: 'TD Garden',
        city: 'Boston',
        state: 'MA',
        postalCode: '02114',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 19,
        slug: 'td-garden',
        heroImagePath:
          'https://static.gotickets.com/a71b4f62-05b5-428c-93c2-9d84b0306e8c.webp',
        singleLineAddress: 'Boston, MA 02114',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '1a533612-a005-413f-9807-2438edf408a4',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273874,
      name: 'Kacey Musgraves',
      venueId: 1815,
      venueConfigurationId: 24823,
      eventTimeLocal: '2024-09-07T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 278208,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-07T23:30:00',
      eventPerformers: [
        {
          id: 324823,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1815,
        name: 'TD Garden',
        city: 'Boston',
        state: 'MA',
        postalCode: '02114',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 19,
        slug: 'td-garden',
        heroImagePath:
          'https://static.gotickets.com/a71b4f62-05b5-428c-93c2-9d84b0306e8c.webp',
        singleLineAddress: 'Boston, MA 02114',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '1a533612-a005-413f-9807-2438edf408a4',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273875,
      name: 'Kacey Musgraves',
      venueId: 1523,
      venueConfigurationId: 24873,
      eventTimeLocal: '2024-09-09T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279145,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-09T23:30:00',
      eventPerformers: [
        {
          id: 324824,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1523,
        name: 'Prudential Center',
        city: 'Newark',
        state: 'NJ',
        postalCode: '07102',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 9,
        slug: 'prudential-center',
        heroImagePath:
          'https://static.gotickets.com/3ac1f6db-bd50-4e19-82d0-20935a779644.webp',
        singleLineAddress: 'Newark, NJ 07102',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '6b7c3a4e-6aa3-440f-8731-db50b3ea5b14',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274044,
      name: 'Kacey Musgraves',
      venueId: 2233,
      venueConfigurationId: 24874,
      eventTimeLocal: '2024-09-11T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-11T23:30:00',
      eventPerformers: [
        {
          id: 325004,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 2233,
        name: 'Van Andel Arena',
        city: 'Grand Rapids',
        state: 'MI',
        postalCode: '49503',
        country: 'US',
        timeZone: 'America/Detroit',
        parentVenue: false,
        parking: false,
        regionId: 108,
        slug: 'van-andel-arena',
        heroImagePath:
          'https://static.gotickets.com/4578b772-c626-4222-9fc9-ed15b1c9213f.webp',
        singleLineAddress: 'Grand Rapids, MI 49503',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '56affdb7-ae4c-41b5-8403-c1ac0e2e7b07',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273881,
      name: 'Kacey Musgraves',
      venueId: 60,
      venueConfigurationId: 24699,
      eventTimeLocal: '2024-09-12T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 371503,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-13T00:30:00',
      eventPerformers: [
        {
          id: 324829,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 60,
        name: 'Allstate Arena',
        city: 'Rosemont',
        state: 'IL',
        postalCode: '60018',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 1,
        slug: 'allstate-arena',
        heroImagePath:
          'https://static.gotickets.com/7a09c0be-b49b-4414-a4ff-3ecda9e5f4bb.webp',
        singleLineAddress: 'Rosemont, IL 60018',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '565248da-99aa-4c03-b6c4-9802a67a61ee',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273993,
      name: 'Kacey Musgraves',
      venueId: 734,
      venueConfigurationId: 23994,
      eventTimeLocal: '2024-09-15T20:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279131,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-16T02:00:00',
      eventPerformers: [
        {
          id: 324944,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 734,
        name: 'Fiddlers Green Amphitheatre',
        city: 'Greenwood Village',
        state: 'CO',
        postalCode: '80111',
        country: 'US',
        timeZone: 'America/Denver',
        parentVenue: false,
        parking: false,
        regionId: 42,
        slug: 'fiddlers-green-amphitheatre',
        singleLineAddress: 'Greenwood Village, CO 80111',
      },
      venueConfiguration: {
        name: 'Concert: GA Pit ',
        svgMapFileName: '61ea8014-2d42-41eb-8bde-d23e5afeabae',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273968,
      name: 'Kacey Musgraves',
      venueId: 1613,
      venueConfigurationId: 24800,
      eventTimeLocal: '2024-09-19T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-20T02:30:00',
      eventPerformers: [
        {
          id: 324919,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1613,
        name: 'Rogers Arena',
        city: 'Vancouver',
        state: 'BC',
        postalCode: 'V6B 6G1',
        country: 'CA',
        timeZone: 'America/Vancouver',
        parentVenue: false,
        parking: false,
        regionId: 61,
        slug: 'rogers-arena',
        heroImagePath:
          'https://static.gotickets.com/4bf15308-a4f0-4e1e-8eb8-39c0e5d1dd8e.webp',
        singleLineAddress: 'Vancouver, BC V6B 6G1',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'f7611de6-7bf0-4746-ab03-8b6133975836',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273888,
      name: 'Kacey Musgraves',
      venueId: 512,
      venueConfigurationId: 24807,
      eventTimeLocal: '2024-09-20T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 275802,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-21T02:30:00',
      eventPerformers: [
        {
          id: 324835,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 512,
        name: 'Climate Pledge Arena',
        city: 'Seattle',
        state: 'WA',
        postalCode: '98109',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 30,
        slug: 'climate-pledge-arena',
        heroImagePath:
          'https://static.gotickets.com/73f19bbc-da9d-46cb-b77d-6abf968648e2.webp',
        singleLineAddress: 'Seattle, WA 98109',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '531b4d20-0f8b-40ef-8695-81c5c8265b4f',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273892,
      name: 'Kacey Musgraves',
      venueId: 843,
      venueConfigurationId: 24702,
      eventTimeLocal: '2024-09-23T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 275812,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-24T02:30:00',
      eventPerformers: [
        {
          id: 324839,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 843,
        name: 'Golden 1 Center',
        city: 'Sacramento',
        state: 'CA',
        postalCode: '95814',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 40,
        slug: 'golden-1-center',
        heroImagePath:
          'https://static.gotickets.com/a90f0e18-0ce0-49f5-adb4-860c409ea44b.webp',
        singleLineAddress: 'Sacramento, CA 95814',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '2f57b980-bac8-4724-ad46-d890d8017de5',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273893,
      name: 'Kacey Musgraves',
      venueId: 472,
      venueConfigurationId: 24801,
      eventTimeLocal: '2024-09-24T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 285151,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-25T02:30:00',
      eventPerformers: [
        {
          id: 324840,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 472,
        name: 'Chase Center',
        city: 'San Francisco',
        state: 'CA',
        postalCode: '94158',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 17,
        slug: 'chase-center',
        heroImagePath:
          'https://static.gotickets.com/ca1f56ec-cf1b-419e-8107-f36ae81ff6fc.webp',
        singleLineAddress: 'San Francisco, CA 94158',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: '66454a4e-90a5-48a0-949e-a806586e3599',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274000,
      name: 'Kacey Musgraves',
      venueId: 626,
      venueConfigurationId: 25804,
      eventTimeLocal: '2024-09-27T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279136,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-28T02:30:00',
      eventPerformers: [
        {
          id: 324951,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 626,
        name: 'Desert Diamond Arena',
        city: 'Glendale',
        state: 'AZ',
        postalCode: '85305',
        country: 'US',
        timeZone: 'America/Phoenix',
        parentVenue: false,
        parking: false,
        regionId: 12,
        slug: 'desert-diamond-arena',
        heroImagePath:
          'https://static.gotickets.com/69e64b35-fc95-4067-84a7-290698304357.webp',
        singleLineAddress: 'Glendale, AZ 85305',
      },
      venueConfiguration: {
        name: 'Concert: Floor GA + Mix (Kacey Musgraves)',
        svgMapFileName: 'b6ab1ab9-1fa1-4105-9e23-d8941a14b4a2',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274002,
      name: 'Kacey Musgraves',
      venueId: 1801,
      venueConfigurationId: 24804,
      eventTimeLocal: '2024-09-28T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 283431,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-29T02:30:00',
      eventPerformers: [
        {
          id: 324953,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1801,
        name: 'T-Mobile Arena',
        city: 'Las Vegas',
        state: 'NV',
        postalCode: '89109',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 10,
        slug: 't-mobile-arena',
        heroImagePath:
          'https://static.gotickets.com/00b13be6-5b73-4941-aa79-10a1dc193c3d.webp',
        singleLineAddress: 'Las Vegas, NV 89109',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: '70bd5bd8-124a-4e52-ab99-04ddfdaca756',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274022,
      name: 'Kacey Musgraves',
      venueId: 1462,
      venueConfigurationId: 25194,
      eventTimeLocal: '2024-10-01T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 282781,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-02T02:30:00',
      eventPerformers: [
        {
          id: 324975,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1462,
        name: 'Pechanga Arena - San Diego',
        city: 'San Diego',
        state: 'CA',
        postalCode: '92110',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 13,
        slug: 'pechanga-arena-san-diego',
        heroImagePath:
          'https://static.gotickets.com/4b47826c-66a8-406d-beba-e52627892294.webp',
        singleLineAddress: 'San Diego, CA 92110',
      },
      venueConfiguration: {
        name: 'Concert: GA Flr (Kacey Musgraves)',
        svgMapFileName: '03b8517e-2816-4b57-abad-5791189cfcd4',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273895,
      name: 'Kacey Musgraves',
      venueId: 1066,
      venueConfigurationId: 28786,
      eventTimeLocal: '2024-10-03T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 276989,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-04T02:30:00',
      eventPerformers: [
        {
          id: 324842,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1066,
        name: 'Kia Forum - Los Angeles',
        city: 'Inglewood',
        state: 'CA',
        postalCode: '90305',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 11,
        slug: 'kia-forum-los-angeles',
        heroImagePath:
          'https://static.gotickets.com/798174b2-5561-4e91-b8cc-d2723a546a96.webp',
        singleLineAddress: 'Inglewood, CA 90305',
      },
      venueConfiguration: {
        name: 'Concert: Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'e28c227d-efde-488e-a7f0-5cb066621b21',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273900,
      name: 'Kacey Musgraves',
      venueId: 1066,
      venueConfigurationId: 28786,
      eventTimeLocal: '2024-10-04T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279143,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-10-05T02:30:00',
      eventPerformers: [
        {
          id: 324848,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1066,
        name: 'Kia Forum - Los Angeles',
        city: 'Inglewood',
        state: 'CA',
        postalCode: '90305',
        country: 'US',
        timeZone: 'America/Los_Angeles',
        parentVenue: false,
        parking: false,
        regionId: 11,
        slug: 'kia-forum-los-angeles',
        heroImagePath:
          'https://static.gotickets.com/798174b2-5561-4e91-b8cc-d2723a546a96.webp',
        singleLineAddress: 'Inglewood, CA 90305',
      },
      venueConfiguration: {
        name: 'Concert: Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'e28c227d-efde-488e-a7f0-5cb066621b21',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273970,
      name: 'Kacey Musgraves',
      venueId: 1490,
      venueConfigurationId: 24808,
      eventTimeLocal: '2024-11-06T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-07T00:30:00',
      eventPerformers: [
        {
          id: 324921,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1490,
        name: 'Place Bell',
        city: 'Laval',
        state: 'QC',
        postalCode: 'H7N 0E4',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'place-bell',
        singleLineAddress: 'Laval, QC H7N 0E4',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '94070c15-78b9-44a0-bfa5-bec2cd125a52',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273972,
      name: 'Kacey Musgraves',
      venueId: 1668,
      venueConfigurationId: 24809,
      eventTimeLocal: '2024-11-07T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 288533,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-08T00:30:00',
      eventPerformers: [
        {
          id: 324923,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1668,
        name: 'Scotiabank Arena',
        city: 'Toronto',
        state: 'ON',
        postalCode: 'M5J 2X2',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 31,
        slug: 'scotiabank-arena',
        heroImagePath:
          'https://static.gotickets.com/24bb712c-ff2d-45fb-8f99-205d59866df0.webp',
        singleLineAddress: 'Toronto, ON M5J 2X2',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '254404f4-7db5-467b-bd05-ef9e6ab991ac',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273902,
      name: 'Kacey Musgraves',
      venueId: 452,
      venueConfigurationId: 24810,
      eventTimeLocal: '2024-11-09T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279138,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-10T00:30:00',
      eventPerformers: [
        {
          id: 324850,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 452,
        name: 'CFG Bank Arena',
        city: 'Baltimore',
        state: 'MD',
        postalCode: '21201',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 20,
        slug: 'cfg-bank-arena',
        singleLineAddress: 'Baltimore, MD 21201',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '7e3145d7-cf37-4ff1-8d7a-0d9a207757fe',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273904,
      name: 'Kacey Musgraves',
      venueId: 1516,
      venueConfigurationId: 24816,
      eventTimeLocal: '2024-11-10T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 275483,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-11T00:30:00',
      eventPerformers: [
        {
          id: 324852,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1516,
        name: 'PPG Paints Arena',
        city: 'Pittsburgh',
        state: 'PA',
        postalCode: '15219',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 7,
        slug: 'ppg-paints-arena',
        singleLineAddress: 'Pittsburgh, PA 15219',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '68a919d7-79da-44d5-a062-d9e5a1b9f3a7',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274041,
      name: 'Kacey Musgraves',
      venueId: 59,
      venueConfigurationId: 25167,
      eventTimeLocal: '2024-11-12T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 285152,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-13T00:30:00',
      eventPerformers: [
        {
          id: 324997,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 59,
        name: 'KFC Yum! Center',
        city: 'Louisville',
        state: 'KY',
        postalCode: '40202',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 48,
        slug: 'kfc-yum-center',
        heroImagePath:
          'https://static.gotickets.com/0681cf7c-c3b2-4beb-a8ba-eadc7d3933ce.webp',
        singleLineAddress: 'Louisville, KY 40202',
      },
      venueConfiguration: {
        name: 'Concert: GA Flr (Kacey Musgraves)',
        svgMapFileName: 'b07bb0bc-d629-416b-8932-9b9b44824105',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273908,
      name: 'Kacey Musgraves',
      venueId: 1666,
      venueConfigurationId: 24819,
      eventTimeLocal: '2024-11-13T19:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 324282,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-14T00:00:00',
      eventPerformers: [
        {
          id: 324856,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1666,
        name: 'Value City Arena at Schottenstein Center',
        city: 'Columbus',
        state: 'OH',
        postalCode: '43210',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 52,
        slug: 'value-city-arena-at-schottenstein-center',
        singleLineAddress: 'Columbus, OH 43210',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: '3620ba85-e18f-4eda-950d-8e6d7444d567',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273911,
      name: 'Kacey Musgraves',
      venueId: 236,
      venueConfigurationId: 24824,
      eventTimeLocal: '2024-11-15T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 280124,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-16T00:30:00',
      eventPerformers: [
        {
          id: 324859,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 236,
        name: 'Barclays Center',
        city: 'Brooklyn',
        state: 'NY',
        postalCode: '11217',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 9,
        slug: 'barclays-center',
        heroImagePath:
          'https://static.gotickets.com/18c67409-ba82-420f-9b9e-9f4461d57728.webp',
        singleLineAddress: 'Brooklyn, NY 11217',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'f28d4a76-648c-44b7-b853-441ac49d4cc6',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273913,
      name: 'Kacey Musgraves',
      venueId: 236,
      venueConfigurationId: 24824,
      eventTimeLocal: '2024-11-16T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 280125,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-17T00:30:00',
      eventPerformers: [
        {
          id: 324862,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 236,
        name: 'Barclays Center',
        city: 'Brooklyn',
        state: 'NY',
        postalCode: '11217',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 9,
        slug: 'barclays-center',
        heroImagePath:
          'https://static.gotickets.com/18c67409-ba82-420f-9b9e-9f4461d57728.webp',
        singleLineAddress: 'Brooklyn, NY 11217',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'f28d4a76-648c-44b7-b853-441ac49d4cc6',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 274027,
      name: 'Kacey Musgraves',
      venueId: 54,
      venueConfigurationId: 25363,
      eventTimeLocal: '2024-11-21T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279149,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-22T01:30:00',
      eventPerformers: [
        {
          id: 324980,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 54,
        name: 'Toyota Center - TX',
        city: 'Houston',
        state: 'TX',
        postalCode: '77002',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 29,
        slug: 'toyota-center-tx',
        heroImagePath:
          'https://static.gotickets.com/32af2f46-f09b-4536-8557-7ad760f925ed.webp',
        singleLineAddress: 'Houston, TX 77002',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'fa1e7bf2-a3d0-41b0-99c0-22bca8b9b7fd',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273915,
      name: 'Kacey Musgraves',
      venueId: 61,
      venueConfigurationId: 24829,
      eventTimeLocal: '2024-11-22T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279122,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-23T01:30:00',
      eventPerformers: [
        {
          id: 324864,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 61,
        name: 'American Airlines Center - TX',
        city: 'Dallas',
        state: 'TX',
        postalCode: '75219',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 27,
        slug: 'american-airlines-center-tx',
        heroImagePath:
          'https://static.gotickets.com/102cbc2c-94b8-4b40-bf8a-4a5ec44fe826.webp',
        singleLineAddress: 'Dallas, TX 75219',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'dcbc006a-cde0-4761-9339-b07103f0d475',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273916,
      name: 'Kacey Musgraves',
      venueId: 61,
      venueConfigurationId: 24829,
      eventTimeLocal: '2024-11-23T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 276517,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-24T01:30:00',
      eventPerformers: [
        {
          id: 324865,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 61,
        name: 'American Airlines Center - TX',
        city: 'Dallas',
        state: 'TX',
        postalCode: '75219',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 27,
        slug: 'american-airlines-center-tx',
        heroImagePath:
          'https://static.gotickets.com/102cbc2c-94b8-4b40-bf8a-4a5ec44fe826.webp',
        singleLineAddress: 'Dallas, TX 75219',
      },
      venueConfiguration: {
        name: 'Concert: No edge stage (Kacey Musgraves)',
        svgMapFileName: 'dcbc006a-cde0-4761-9339-b07103f0d475',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273834,
      name: 'Kacey Musgraves',
      venueId: 1305,
      venueConfigurationId: 24826,
      eventTimeLocal: '2024-11-26T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 275008,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-27T01:30:00',
      eventPerformers: [
        {
          id: 324784,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1305,
        name: 'Moody Center ATX',
        city: 'Austin',
        state: 'TX',
        postalCode: '78712',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 28,
        slug: 'moody-center-atx',
        heroImagePath:
          'https://static.gotickets.com/7e2d804d-5b01-4b29-b9d7-86bee86c4a7c.webp',
        singleLineAddress: 'Austin, TX 78712',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'a02f4519-9e56-4dd6-aad8-fc803dcff1f8',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273920,
      name: 'Kacey Musgraves',
      venueId: 1305,
      venueConfigurationId: 24826,
      eventTimeLocal: '2024-11-27T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 275009,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-28T01:30:00',
      eventPerformers: [
        {
          id: 324868,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1305,
        name: 'Moody Center ATX',
        city: 'Austin',
        state: 'TX',
        postalCode: '78712',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 28,
        slug: 'moody-center-atx',
        heroImagePath:
          'https://static.gotickets.com/7e2d804d-5b01-4b29-b9d7-86bee86c4a7c.webp',
        singleLineAddress: 'Austin, TX 78712',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'a02f4519-9e56-4dd6-aad8-fc803dcff1f8',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273921,
      name: 'Kacey Musgraves',
      venueId: 34,
      venueConfigurationId: 24827,
      eventTimeLocal: '2024-11-29T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 285147,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-11-30T00:30:00',
      eventPerformers: [
        {
          id: 324869,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 34,
        name: 'Amalie Arena',
        city: 'Tampa',
        state: 'FL',
        postalCode: '33602',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 18,
        slug: 'amalie-arena',
        heroImagePath:
          'https://static.gotickets.com/235ad4cf-c51d-4f88-8269-1d65463e1aca.webp',
        singleLineAddress: 'Tampa, FL 33602',
      },
      venueConfiguration: {
        name: 'UNIQUE Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: '893f34cc-8d48-4241-a36d-cb99bcaec4af',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273930,
      name: 'Kacey Musgraves',
      venueId: 891,
      venueConfigurationId: 24825,
      eventTimeLocal: '2024-11-30T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-12-01T00:30:00',
      eventPerformers: [
        {
          id: 324878,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 891,
        name: 'Hard Rock Live at The Seminole Hard Rock Hotel and Casino - Hollywood',
        city: 'Hollywood',
        state: 'FL',
        postalCode: '33314',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 15,
        slug: 'hard-rock-live-at-the-seminole-hard-rock-hotel-and-casino-hollywood',
        heroImagePath:
          'https://static.gotickets.com/2096e7a4-aa99-4858-abe6-ea0afb2a43ba.webp',
        singleLineAddress: 'Hollywood, FL 33314',
      },
      venueConfiguration: {
        name: 'Pit',
        svgMapFileName: '961974a0-f53e-4304-b718-d8033d04d820',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273933,
      name: 'Kacey Musgraves',
      venueId: 161,
      venueConfigurationId: 24828,
      eventTimeLocal: '2024-12-02T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279141,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-12-03T00:30:00',
      eventPerformers: [
        {
          id: 324881,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 161,
        name: 'Kia Center (Formerly Amway Center)',
        city: 'Orlando',
        state: 'FL',
        postalCode: '32801',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 16,
        slug: 'kia-center-formerly-amway-center',
        heroImagePath:
          'https://static.gotickets.com/9bb520cd-f642-4f01-ada2-df5fdbbcbd1f.webp',
        singleLineAddress: 'Orlando, FL 32801',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: '85467ed3-53e3-4ab1-90c0-e3fc2899d37b',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273941,
      name: 'Kacey Musgraves',
      venueId: 1751,
      venueConfigurationId: 24830,
      eventTimeLocal: '2024-12-05T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279148,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-12-06T00:30:00',
      eventPerformers: [
        {
          id: 324889,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 1751,
        name: 'Spectrum Center',
        city: 'Charlotte',
        state: 'NC',
        postalCode: '28202',
        country: 'US',
        timeZone: 'America/New_York',
        parentVenue: false,
        parking: false,
        regionId: 24,
        slug: 'spectrum-center',
        heroImagePath:
          'https://static.gotickets.com/6819e0e1-7974-4c7a-a372-d0a33f456ebe.webp',
        singleLineAddress: 'Charlotte, NC 28202',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'c951bc6d-03fc-4117-adac-39650a4661c0',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273943,
      name: 'Kacey Musgraves',
      venueId: 345,
      venueConfigurationId: 24831,
      eventTimeLocal: '2024-12-06T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279129,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-12-07T01:30:00',
      eventPerformers: [
        {
          id: 324891,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 345,
        name: 'Bridgestone Arena',
        city: 'Nashville',
        state: 'TN',
        postalCode: '37203',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 2,
        slug: 'bridgestone-arena',
        heroImagePath:
          'https://static.gotickets.com/d52cacaf-8ade-41c7-83db-0a6f7b2f743a.webp',
        singleLineAddress: 'Nashville, TN 37203',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'a2aa6e5e-f538-48bb-98e3-0fa82855dc0b',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273945,
      name: 'Kacey Musgraves',
      venueId: 345,
      venueConfigurationId: 24831,
      eventTimeLocal: '2024-12-07T19:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 279130,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-12-08T01:30:00',
      eventPerformers: [
        {
          id: 324894,
          performerId: 5981,
          master: true,
          performer: {
            id: 5981,
            name: 'Kacey Musgraves',
            primaryCategoryId: 138,
            parking: false,
            slug: 'kacey-musgraves-tickets',
            heroImagePath:
              'https://static.gotickets.com/ff78bdf5-61f4-4065-a6ce-f8544a35e7d3.webp',
            primaryCategory: {
              id: 138,
              name: 'Country and Folk',
              eventType: 'CONCERTS',
            },
            cmsPageId: 591,
          },
        },
      ],
      venue: {
        id: 345,
        name: 'Bridgestone Arena',
        city: 'Nashville',
        state: 'TN',
        postalCode: '37203',
        country: 'US',
        timeZone: 'America/Chicago',
        parentVenue: false,
        parking: false,
        regionId: 2,
        slug: 'bridgestone-arena',
        heroImagePath:
          'https://static.gotickets.com/d52cacaf-8ade-41c7-83db-0a6f7b2f743a.webp',
        singleLineAddress: 'Nashville, TN 37203',
      },
      venueConfiguration: {
        name: 'Concert: Rounded Stage + GA Floor (Kacey Musgraves)',
        svgMapFileName: 'a2aa6e5e-f538-48bb-98e3-0fa82855dc0b',
        generalAdmission: false,
        staticMap: false,
      },
    },
  ],
}
