import type { components } from '@/contracts/generated/maverick-schema'

export const eventFromSamePerformer = {
  id: 343127,
  name: 'Missy Elliott',
  venueId: 4650,
  venueConfigurationId: 29333,
  eventTimeLocal: '2024-08-17T19:00:00',
  timeTbd: false,
  dateTbd: false,
  parking: false,
  parkingEventId: 392935,
  ifNecessary: false,
  multiDate: false,
  eventTimeUtc: '2024-08-17T23:00:00',
  eventPerformers: [
    {
      id: 401986,
      performerId: 11571,
      master: true,
      performer: {
        id: 11571,
        name: 'Kid Cudi',
        primaryCategoryId: 145,
        parking: false,
        slug: 'kid-cudi-tickets',
        heroImagePath:
          'https://static.gotickets.com/f3deff4f-9982-412b-a5c6-4d26ad0dfefd.webp',
        primaryCategory: {
          id: 145,
          name: 'Rap/Hip Hop',
          eventType: 'CONCERTS',
          slug: 'rap-hip-hop',
        },
        cmsPageId: 581,
      },
    },
  ],
  venue: {
    addr1: 'Lorem',
    id: 4650,
    name: 'Bell Centre',
    city: 'Montréal',
    state: 'QC',
    postalCode: 'H3B 5E8',
    country: 'CA',
    timeZone: 'America/Toronto',
    parentVenue: false,
    parking: false,
    regionId: 64,
    slug: 'bell-centre',
    heroImagePath:
      'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
    singleLineAddress: 'Montréal, QC H3B 5E8',
  },
  venueConfiguration: {
    name: 'UNIQUE Concert: Unique stage with Curved edges (Missy Elliott)',
    svgMapFileName: 'cfe8f23a-dcc7-4a3a-93fe-f87ebeb263c1',
    generalAdmission: false,
    staticMap: false,
  },
}

export const moreAtThisVenueMock: {
  adGroupEntityResult: components['schemas']['AdGroupEntityResult']
  events: components['schemas']['Event'][]
} = {
  adGroupEntityResult: {
    performer: {
      id: 11571,
      name: 'Kid Cudi',
      primaryCategoryId: 145,
      parking: false,
      slug: 'kid-cudi-tickets',
      heroImagePath:
        'https://static.gotickets.com/f3deff4f-9982-412b-a5c6-4d26ad0dfefd.webp',
      primaryCategory: {
        id: 145,
        name: 'Rap/Hip Hop',
        eventType: 'CONCERTS',
        slug: 'rap-hip-hop',
      },
      cmsPageId: 581,
    },
    venue: {
      addr1: 'Lorem',
      country: 'CA',
      city: 'Montréal',
      state: 'QC',
      id: 4650,
      name: 'Bell Centre',
      parentVenue: false,
      parking: false,
      slug: 'bell-centre',
      heroImagePath:
        'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
      singleLineAddress: '',
    },
    region: {
      id: 64,
      name: 'Montreal',
      venueRadius: 0,
      heroImagePath: '4bebd4a6-488c-4d8b-86f0-8207636575a5.webp',
      slug: 'montreal-events',
    },
  },
  events: [
    {
      id: 237397,
      name: 'Lamb of God and Mastodon',
      venueId: 4650,
      venueConfigurationId: 5358,
      seasonTicket: false,
      eventTimeLocal: '2024-08-01T18:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 433616,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-08-01T22:00:00',
      eventPerformers: [
        {
          id: 282830,
          performerId: 11911,
          master: true,
          performer: {
            id: 11911,
            name: 'Lamb of God',
            primaryCategoryId: 233,
            parking: false,
            slug: 'lamb-of-god-tickets',
            heroImagePath:
              'https://static.gotickets.com/11d7da56-a650-4e51-8c3a-299fbe823b24.webp',
            primaryCategory: {
              id: 233,
              name: 'Heavy Metal',
              eventType: 'CONCERTS',
            },
            cmsPageId: 455,
          },
        },
        {
          id: 282831,
          performerId: 6991,
          master: false,
          performer: {
            id: 6991,
            name: 'Mastodon',
            primaryCategoryId: 137,
            parking: false,
            slug: 'mastodon-tickets',
            heroImagePath:
              'https://static.gotickets.com/669559da-ef48-4b31-810a-1ff02dbd1a9d.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
            cmsPageId: 456,
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 5358,
        venueId: 4650,
        name: 'Concert: GA Floor (Maitre Gims)',
        svgMapFileName: '6e0fac66-4a53-4581-bd8a-e61bc9b0c43b',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 225541,
      name: 'Heart with Cheap Trick',
      venueId: 4650,
      seasonTicket: false,
      venueConfigurationId: 20348,
      eventTimeLocal: '2024-08-08T20:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 294605,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-08-09T00:00:00',
      eventPerformers: [
        {
          id: 269656,
          performerId: 6975,
          master: true,
          performer: {
            id: 6975,
            name: 'Heart',
            primaryCategoryId: 137,
            parking: false,
            slug: 'heart',
            heroImagePath:
              'https://static.gotickets.com/5c427637-68e1-477d-8b89-35a4f83f8bea.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
          },
        },
        {
          id: 291337,
          performerId: 6958,
          master: false,
          performer: {
            id: 6958,
            name: 'Cheap Trick',
            primaryCategoryId: 137,
            parking: false,
            slug: 'cheap-trick',
            heroImagePath:
              'https://static.gotickets.com/5fa42dd7-a6d5-44ab-b375-9483c3885322.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 5358,
        venueId: 4650,
        name: 'Concert: Nord (Heart)',
        svgMapFileName: '1058e6f7-047b-4c0d-b52a-d6f46b595448',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 338852,
      name: 'Billy Idol',
      venueId: 4650,
      venueConfigurationId: 20348,
      eventTimeLocal: '2024-08-16T20:00:00',
      timeTbd: false,
      seasonTicket: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 392934,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-08-17T00:00:00',
      eventPerformers: [
        {
          id: 397425,
          performerId: 695,
          master: true,
          performer: {
            id: 695,
            name: 'Billy Idol',
            primaryCategoryId: 137,
            parking: false,
            slug: 'billy-idol',
            heroImagePath:
              'https://static.gotickets.com/31aa6040-9f70-4982-a849-15e687418eba.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
            cmsPageId: 784,
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 5358,
        venueId: 4650,
        name: 'Concert: Nord (Heart)',
        svgMapFileName: '1058e6f7-047b-4c0d-b52a-d6f46b595448',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 273894,
      seasonTicket: false,
      name: 'Cage The Elephant',
      venueId: 4650,
      venueConfigurationId: 20348,
      eventTimeLocal: '2024-08-26T18:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 294606,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-08-26T22:30:00',
      eventPerformers: [
        {
          id: 324841,
          performerId: 6771,
          master: true,
          performer: {
            id: 6771,
            name: 'Cage The Elephant',
            primaryCategoryId: 137,
            parking: false,
            slug: 'cage-the-elephant-tickets',
            heroImagePath:
              'https://static.gotickets.com/5d56290f-f4db-44d8-ac2d-271a43498deb.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
            cmsPageId: 590,
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 20348,
        venueId: 4650,
        name: 'Concert: Nord (Heart)',
        svgMapFileName: '1058e6f7-047b-4c0d-b52a-d6f46b595448',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 345712,
      name: 'Deep Purple',
      venueId: 4650,
      seasonTicket: false,
      venueConfigurationId: 29516,
      eventTimeLocal: '2024-08-27T18:30:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 392936,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-08-27T22:30:00',
      eventPerformers: [
        {
          id: 404663,
          performerId: 6959,
          master: true,
          performer: {
            id: 6959,
            name: 'Deep Purple',
            primaryCategoryId: 137,
            parking: false,
            slug: 'deep-purple',
            heroImagePath:
              'https://static.gotickets.com/7d676c6b-a75e-4443-af11-29636ba5016e.webp',
            primaryCategory: {
              id: 137,
              name: 'Rock',
              eventType: 'CONCERTS',
            },
            cmsPageId: 920,
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 20348,
        venueId: 4650,
        name: 'Concert: Scene + Nord + Mix (Deep Purple)',
        svgMapFileName: '7cbb9bc2-8af3-4c5e-99f6-3226a73c4b67',
        generalAdmission: false,
        staticMap: false,
      },
    },
    {
      id: 272514,
      name: 'Cigarettes After Sex',
      venueId: 4650,
      seasonTicket: false,
      venueConfigurationId: 24631,
      eventTimeLocal: '2024-08-31T20:00:00',
      timeTbd: false,
      dateTbd: false,
      parking: false,
      parkingEventId: 294607,
      ifNecessary: false,
      multiDate: false,
      eventTimeUtc: '2024-09-01T00:00:00',
      eventPerformers: [
        {
          id: 323299,
          performerId: 15050,
          master: true,
          performer: {
            id: 15050,
            name: 'Cigarettes After Sex',
            primaryCategoryId: 141,
            parking: false,
            slug: 'cigarettes-after-sex-tickets',
            heroImagePath:
              'https://static.gotickets.com/23cbd680-8cbd-4cc3-9e5e-b1daa7415547.webp',
            primaryCategory: {
              id: 141,
              name: 'Pop',
              eventType: 'CONCERTS',
            },
            cmsPageId: 589,
          },
        },
      ],
      venue: {
        addr1: 'Lorem',
        id: 4650,
        name: 'Bell Centre',
        city: 'Montréal',
        state: 'QC',
        postalCode: 'H3B 5E8',
        country: 'CA',
        timeZone: 'America/Toronto',
        parentVenue: false,
        parking: false,
        regionId: 64,
        slug: 'bell-centre',
        heroImagePath:
          'https://static.gotickets.com/5f2f1958-36ce-40a1-81cd-76b697690246.webp',
        singleLineAddress: 'Montréal, QC H3B 5E8',
      },
      venueConfiguration: {
        id: 20348,
        venueId: 4650,
        name: 'Concert: Cigarettes after sex',
        svgMapFileName: 'f507590d-874a-436c-a589-3619e1454163',
        generalAdmission: false,
        staticMap: false,
      },
    },
  ],
}
