import type { components, paths } from '@/contracts/generated/maverick-schema';

export interface GetCmsOptions {
  init?: Omit<RequestInit, 'body'>;
  params: paths['/rest/cms']['get']['parameters'];
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export async function getCms({ init, params }: GetCmsOptions) {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  return response as unknown as CmsPathResponse;
}

interface CmsPathResponse {
  data: components['schemas']['CmsPathResponse'];
}

const response = {
  data: {
    pageId: 1052,
    path: 'billie-eilish',
    title: 'Billie Eilish Tickets',
    metaDescription:
      'The best Billie Eilish tickets can be tough to track down, but GoTickets can help score fantastic seats. Search our secure marketplace today!',
    metaKeywords:
      'billie eilish tickets, billie eilish, billie eilish concert, billie eilish concert tickets, billie eilish concert dates, billie eilish tour, billie eilish tour tickets, billie eilish tour dates, tickets for billie eilish, tickets to billie eilish, billie eilish show, billie eilish live',
    performer: {
      id: 8077,
      name: 'Billie Eilish',
      primaryCategoryId: 141,
      parking: false,
      parkingPerformerId: 32905,
      slug: 'billie-eilish',
      heroImagePath: 'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
      primaryCategory: {
        id: 141,
        name: 'Pop',
        parentId: 6,
        eventType: 'CONCERTS',
        slug: 'pop',
        heroImagePath: 'https://static.gotickets.com/472edace-232c-4c65-ab75-959c6463eece.webp',
        performerHeroImagePath:
          'https://static.gotickets.com/370c2f54-f6c2-478e-a0c1-e84593e3e6e1.webp',
      },
      cmsPageId: 1052,
      parkingPerformer: {
        id: 32905,
        name: 'Billie Eilish Parking',
        parking: true,
        slug: 'billie-eilish-parking',
      },
      childPerformers: [],
      popularity: 1,
      performerStats: {
        clicks1Day: 1000,
        clicks7Day: 10000,
        clicks30Day: 10000,
      },
    },
    template: 'performer-page',
    events: [
      {
        doc: 0,
        fields: 0,
        id: 380516,
        name: 'Billie Eilish',
        venueId: 7078,
        venueConfigurationId: 33609,
        eventTimeLocal: '2025-06-01T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-06-01T17:00:00',
        eventPerformers: [
          {
            id: 442361,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 7078,
          name: 'O2 Arena - Prague',
          city: 'Prague',
          state: 'Hlavní město Praha',
          postalCode: '190 00',
          country: 'CZ',
          latitude: 50.10482,
          longitude: 14.49363,
          capacity: 18000,
          timeZone: 'Europe/Prague',
          parentVenue: false,
          parking: false,
          slug: 'o2-arena-prague',
          popularity: 10,
          singleLineAddress: 'Prague, Hlavní město Praha 190 00',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: 'f0bda2e9-371e-4a73-a498-84e5f0adfb42',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        daysToEvent: 3,
        pricingType: 'DEFAULT',
        availableTickets: 3,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380495,
        name: 'Billie Eilish',
        venueId: 5953,
        venueConfigurationId: 33134,
        eventTimeLocal: '2025-06-15T20:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-06-15T18:00:00',
        eventPerformers: [
          {
            id: 442340,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5953,
          name: 'Palau Sant Jordi',
          city: 'Barcelona',
          state: 'N/A',
          postalCode: '08038',
          country: 'ES',
          latitude: 41.36337,
          longitude: 2.15259,
          capacity: 17960,
          timeZone: 'Europe/Madrid',
          parentVenue: false,
          parking: false,
          slug: 'palau-sant-jordi',
          popularity: 10,
          singleLineAddress: 'Barcelona, N/A 08038',
        },
        venueConfiguration: {
          name: 'Concert: Stage on center (Billie Eilish)',
          svgMapFileName: 'bc260920-2806-4c95-a87d-8a2c86949753',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        daysToEvent: 17,
        pricingType: 'DEFAULT',
        availableTickets: 6,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380494,
        name: 'Billie Eilish',
        venueId: 5961,
        venueConfigurationId: 32489,
        eventTimeLocal: '2025-07-07T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-07T18:00:00',
        eventPerformers: [
          {
            id: 442339,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5961,
          name: 'OVO Hydro',
          city: 'Glasgow',
          state: 'SCO',
          postalCode: 'G3 8YW',
          country: 'GB',
          latitude: 55.85962,
          longitude: -4.28559,
          capacity: 14300,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 93,
          slug: 'ovo-hydro',
          popularity: 9,
          singleLineAddress: 'Glasgow, SCO G3 8YW',
        },
        venueConfiguration: {
          name: 'Concert: Floor Seating (Billie Eilish)',
          svgMapFileName: '65b0e7e0-d8e5-41e1-958c-b55e879d2ae5',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 39,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 13,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380492,
        name: 'Billie Eilish',
        venueId: 5961,
        venueConfigurationId: 32489,
        eventTimeLocal: '2025-07-08T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-08T18:00:00',
        eventPerformers: [
          {
            id: 442337,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5961,
          name: 'OVO Hydro',
          city: 'Glasgow',
          state: 'SCO',
          postalCode: 'G3 8YW',
          country: 'GB',
          latitude: 55.85962,
          longitude: -4.28559,
          capacity: 14300,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 93,
          slug: 'ovo-hydro',
          popularity: 9,
          singleLineAddress: 'Glasgow, SCO G3 8YW',
        },
        venueConfiguration: {
          name: 'Concert: Floor Seating (Billie Eilish)',
          svgMapFileName: '65b0e7e0-d8e5-41e1-958c-b55e879d2ae5',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 40,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 16,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380485,
        name: 'Billie Eilish',
        venueId: 5959,
        venueConfigurationId: 33614,
        eventTimeLocal: '2025-07-10T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-10T18:00:00',
        eventPerformers: [
          {
            id: 442330,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5959,
          name: 'O2 Arena - London',
          city: 'London',
          state: 'England',
          postalCode: 'SE10 0DX',
          country: 'GB',
          latitude: 51.50304,
          longitude: 0.00315,
          capacity: 20000,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 94,
          slug: 'o2-arena-london',
          popularity: 4,
          singleLineAddress: 'London, England SE10 0DX',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: '2ed1e8b3-37ca-441f-ae54-66285eb5d70a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-05-02T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 42,
        daysToOnsale: -390,
        daysToPresale: -391,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 2,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380477,
        name: 'Billie Eilish',
        venueId: 5959,
        venueConfigurationId: 33614,
        eventTimeLocal: '2025-07-11T18:30:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 604059,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-11T17:30:00',
        eventPerformers: [
          {
            id: 442322,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5959,
          name: 'O2 Arena - London',
          city: 'London',
          state: 'England',
          postalCode: 'SE10 0DX',
          country: 'GB',
          latitude: 51.50304,
          longitude: 0.00315,
          capacity: 20000,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 94,
          slug: 'o2-arena-london',
          popularity: 4,
          singleLineAddress: 'London, England SE10 0DX',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: '2ed1e8b3-37ca-441f-ae54-66285eb5d70a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 43,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 9,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380371,
        name: 'Billie Eilish',
        venueId: 5959,
        venueConfigurationId: 33614,
        eventTimeLocal: '2025-07-13T17:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-13T16:00:00',
        eventPerformers: [
          {
            id: 442216,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5959,
          name: 'O2 Arena - London',
          city: 'London',
          state: 'England',
          postalCode: 'SE10 0DX',
          country: 'GB',
          latitude: 51.50304,
          longitude: 0.00315,
          capacity: 20000,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 94,
          slug: 'o2-arena-london',
          popularity: 4,
          singleLineAddress: 'London, England SE10 0DX',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: '2ed1e8b3-37ca-441f-ae54-66285eb5d70a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        daysToEvent: 45,
        pricingType: 'DEFAULT',
        availableTickets: 1,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380252,
        name: 'Billie Eilish',
        venueId: 5959,
        venueConfigurationId: 33614,
        eventTimeLocal: '2025-07-16T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-16T18:00:00',
        eventPerformers: [
          {
            id: 442097,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5959,
          name: 'O2 Arena - London',
          city: 'London',
          state: 'England',
          postalCode: 'SE10 0DX',
          country: 'GB',
          latitude: 51.50304,
          longitude: 0.00315,
          capacity: 20000,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 94,
          slug: 'o2-arena-london',
          popularity: 4,
          singleLineAddress: 'London, England SE10 0DX',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: '2ed1e8b3-37ca-441f-ae54-66285eb5d70a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 48,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 1,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380251,
        name: 'Billie Eilish',
        venueId: 5959,
        venueConfigurationId: 33614,
        eventTimeLocal: '2025-07-17T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 783290,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-17T18:00:00',
        eventPerformers: [
          {
            id: 442096,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 5959,
          name: 'O2 Arena - London',
          city: 'London',
          state: 'England',
          postalCode: 'SE10 0DX',
          country: 'GB',
          latitude: 51.50304,
          longitude: 0.00315,
          capacity: 20000,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          regionId: 94,
          slug: 'o2-arena-london',
          popularity: 4,
          singleLineAddress: 'London, England SE10 0DX',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: With a center stage (Billie Eilish)',
          svgMapFileName: '2ed1e8b3-37ca-441f-ae54-66285eb5d70a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-05-02T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 49,
        daysToOnsale: -390,
        daysToPresale: -391,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 10,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380245,
        name: 'Billie Eilish',
        venueId: 6030,
        venueConfigurationId: 40939,
        eventTimeLocal: '2025-07-19T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-19T18:00:00',
        eventPerformers: [
          {
            id: 442090,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 6030,
          name: 'Co-op Live',
          city: 'Manchester',
          state: 'ENG',
          country: 'GB',
          capacity: 23500,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          slug: 'co-op-live',
          popularity: 6,
          singleLineAddress: 'Manchester, ENG',
        },
        venueConfiguration: {
          name: 'Concert: Center Stage + GA Floor (Billie Eilish)',
          svgMapFileName: '97d11a84-d3fe-4715-a120-aa7ba856914f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 51,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 4,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380244,
        name: 'Billie Eilish',
        venueId: 6030,
        venueConfigurationId: 40939,
        eventTimeLocal: '2025-07-20T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-20T18:00:00',
        eventPerformers: [
          {
            id: 442089,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 6030,
          name: 'Co-op Live',
          city: 'Manchester',
          state: 'ENG',
          country: 'GB',
          capacity: 23500,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          slug: 'co-op-live',
          popularity: 6,
          singleLineAddress: 'Manchester, ENG',
        },
        venueConfiguration: {
          name: 'Concert: Center Stage + GA Floor (Billie Eilish)',
          svgMapFileName: '97d11a84-d3fe-4715-a120-aa7ba856914f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-05-02T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 52,
        daysToOnsale: -390,
        daysToPresale: -391,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 14,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380228,
        name: 'Billie Eilish',
        venueId: 6030,
        venueConfigurationId: 40939,
        eventTimeLocal: '2025-07-22T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-22T18:00:00',
        eventPerformers: [
          {
            id: 442073,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 6030,
          name: 'Co-op Live',
          city: 'Manchester',
          state: 'ENG',
          country: 'GB',
          capacity: 23500,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          slug: 'co-op-live',
          popularity: 6,
          singleLineAddress: 'Manchester, ENG',
        },
        venueConfiguration: {
          name: 'Concert: Center Stage + GA Floor (Billie Eilish)',
          svgMapFileName: '97d11a84-d3fe-4715-a120-aa7ba856914f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-05-02T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 54,
        daysToOnsale: -390,
        daysToPresale: -391,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 4,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 380225,
        name: 'Billie Eilish',
        venueId: 6030,
        venueConfigurationId: 40939,
        eventTimeLocal: '2025-07-23T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-07-23T18:00:00',
        eventPerformers: [
          {
            id: 442070,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 6030,
          name: 'Co-op Live',
          city: 'Manchester',
          state: 'ENG',
          country: 'GB',
          capacity: 23500,
          timeZone: 'Europe/London',
          parentVenue: false,
          parking: false,
          slug: 'co-op-live',
          popularity: 6,
          singleLineAddress: 'Manchester, ENG',
        },
        venueConfiguration: {
          name: 'Concert: Center Stage + GA Floor (Billie Eilish)',
          svgMapFileName: '97d11a84-d3fe-4715-a120-aa7ba856914f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2024-05-03T07:00:00',
        lastPresaleTimeLocal: '2024-04-30T07:00:00',
        firstOnSaleTimeLocal: '2024-05-03T07:00:00',
        daysToEvent: 55,
        daysToOnsale: -390,
        daysToPresale: -393,
        daysUntilFirstOnSale: -390,
        pricingType: 'DEFAULT',
        availableTickets: 9,
        percentInventoryAvailable: 0,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022553,
        name: 'Billie Eilish',
        venueId: 2482,
        venueConfigurationId: 62321,
        eventTimeLocal: '2025-10-09T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022724,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-09T23:00:00',
        eventPerformers: [
          {
            id: 1208309,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2482,
          name: 'Kaseya Center',
          city: 'Miami',
          state: 'FL',
          postalCode: '33132',
          country: 'US',
          latitude: 25.7814,
          longitude: -80.18697,
          capacity: 19600,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 15,
          slug: 'kaseya-center',
          heroImagePath: 'https://static.gotickets.com/a311ceb9-0b54-4bb6-a160-021d029d722c.webp',
          popularity: 1,
          singleLineAddress: 'Miami, FL 33132',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'acfc51d3-5c46-4864-9400-7fa9ea9d6542',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 133,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 4258,
        percentInventoryAvailable: 0.22,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022556,
        name: 'Billie Eilish',
        venueId: 2482,
        venueConfigurationId: 62321,
        eventTimeLocal: '2025-10-11T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022725,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-11T23:00:00',
        eventPerformers: [
          {
            id: 1208314,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2482,
          name: 'Kaseya Center',
          city: 'Miami',
          state: 'FL',
          postalCode: '33132',
          country: 'US',
          latitude: 25.7814,
          longitude: -80.18697,
          capacity: 19600,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 15,
          slug: 'kaseya-center',
          heroImagePath: 'https://static.gotickets.com/a311ceb9-0b54-4bb6-a160-021d029d722c.webp',
          popularity: 1,
          singleLineAddress: 'Miami, FL 33132',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'acfc51d3-5c46-4864-9400-7fa9ea9d6542',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 135,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 5209,
        percentInventoryAvailable: 0.27,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022558,
        name: 'Billie Eilish',
        venueId: 2482,
        venueConfigurationId: 62321,
        eventTimeLocal: '2025-10-12T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022726,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-12T23:00:00',
        eventPerformers: [
          {
            id: 1208316,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2482,
          name: 'Kaseya Center',
          city: 'Miami',
          state: 'FL',
          postalCode: '33132',
          country: 'US',
          latitude: 25.7814,
          longitude: -80.18697,
          capacity: 19600,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 15,
          slug: 'kaseya-center',
          heroImagePath: 'https://static.gotickets.com/a311ceb9-0b54-4bb6-a160-021d029d722c.webp',
          popularity: 1,
          singleLineAddress: 'Miami, FL 33132',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'acfc51d3-5c46-4864-9400-7fa9ea9d6542',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 136,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 4606,
        percentInventoryAvailable: 0.24,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022561,
        name: 'Billie Eilish',
        venueId: 161,
        venueConfigurationId: 62324,
        eventTimeLocal: '2025-10-14T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022560,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-14T23:00:00',
        eventPerformers: [
          {
            id: 1208320,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 161,
          name: 'Kia Center',
          city: 'Orlando',
          state: 'FL',
          postalCode: '32801',
          country: 'US',
          latitude: 28.53922,
          longitude: -81.38385,
          capacity: 20000,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 16,
          slug: 'kia-center',
          heroImagePath: 'https://static.gotickets.com/9bb520cd-f642-4f01-ada2-df5fdbbcbd1f.webp',
          popularity: 1,
          singleLineAddress: 'Orlando, FL 32801',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '483cee32-0134-4893-811f-7403a3bca584',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 138,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 2371,
        percentInventoryAvailable: 0.12,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022563,
        name: 'Billie Eilish',
        venueId: 1493,
        venueConfigurationId: 62330,
        eventTimeLocal: '2025-10-16T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022562,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-16T23:00:00',
        eventPerformers: [
          {
            id: 1208322,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1493,
          name: 'Lenovo Center',
          city: 'Raleigh',
          state: 'NC',
          postalCode: '27607',
          country: 'US',
          latitude: 35.80333,
          longitude: -78.7218,
          capacity: 20000,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 74,
          slug: 'lenovo-center',
          heroImagePath: 'https://static.gotickets.com/4d08d067-9904-4c41-b477-a38bf3c138cd.webp',
          popularity: 1,
          singleLineAddress: 'Raleigh, NC 27607',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '12186a48-74dd-4e02-8368-a36125da828b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 140,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 4606,
        percentInventoryAvailable: 0.23,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022565,
        name: 'Billie Eilish',
        venueId: 1493,
        venueConfigurationId: 62330,
        eventTimeLocal: '2025-10-17T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022564,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-17T23:00:00',
        eventPerformers: [
          {
            id: 1208324,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1493,
          name: 'Lenovo Center',
          city: 'Raleigh',
          state: 'NC',
          postalCode: '27607',
          country: 'US',
          latitude: 35.80333,
          longitude: -78.7218,
          capacity: 20000,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 74,
          slug: 'lenovo-center',
          heroImagePath: 'https://static.gotickets.com/4d08d067-9904-4c41-b477-a38bf3c138cd.webp',
          popularity: 1,
          singleLineAddress: 'Raleigh, NC 27607',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '12186a48-74dd-4e02-8368-a36125da828b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 141,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 4821,
        percentInventoryAvailable: 0.24,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022566,
        name: 'Billie Eilish',
        venueId: 1751,
        venueConfigurationId: 62322,
        eventTimeLocal: '2025-10-19T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022918,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-19T23:00:00',
        eventPerformers: [
          {
            id: 1208325,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1751,
          name: 'Spectrum Center',
          city: 'Charlotte',
          state: 'NC',
          postalCode: '28202',
          country: 'US',
          latitude: 35.2252,
          longitude: -80.83935,
          capacity: 17500,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 24,
          slug: 'spectrum-center',
          heroImagePath: 'https://static.gotickets.com/6819e0e1-7974-4c7a-a372-d0a33f456ebe.webp',
          popularity: 1,
          singleLineAddress: 'Charlotte, NC 28202',
        },
        venueConfiguration: {
          name: ' UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '608a7bf8-c1f3-4512-8416-1cb54e5bae4b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 143,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3795,
        percentInventoryAvailable: 0.22,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022570,
        name: 'Billie Eilish',
        venueId: 1751,
        venueConfigurationId: 62322,
        eventTimeLocal: '2025-10-20T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022569,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-20T23:00:00',
        eventPerformers: [
          {
            id: 1208330,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1751,
          name: 'Spectrum Center',
          city: 'Charlotte',
          state: 'NC',
          postalCode: '28202',
          country: 'US',
          latitude: 35.2252,
          longitude: -80.83935,
          capacity: 17500,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 24,
          slug: 'spectrum-center',
          heroImagePath: 'https://static.gotickets.com/6819e0e1-7974-4c7a-a372-d0a33f456ebe.webp',
          popularity: 1,
          singleLineAddress: 'Charlotte, NC 28202',
        },
        venueConfiguration: {
          name: ' UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '608a7bf8-c1f3-4512-8416-1cb54e5bae4b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 144,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 4541,
        percentInventoryAvailable: 0.26,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022571,
        name: 'Billie Eilish',
        venueId: 2288,
        venueConfigurationId: 62326,
        eventTimeLocal: '2025-10-23T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1027594,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-23T23:00:00',
        eventPerformers: [
          {
            id: 1208331,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2288,
          name: 'Wells Fargo Center-PA',
          city: 'Philadelphia',
          state: 'PA',
          postalCode: '19148',
          country: 'US',
          latitude: 39.9012,
          longitude: -75.17198,
          capacity: 21000,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 8,
          slug: 'wells-fargo-center-pa',
          heroImagePath: 'https://static.gotickets.com/99ec9958-2d0a-43f3-af81-60b863fe2fdd.webp',
          popularity: 1,
          singleLineAddress: 'Philadelphia, PA 19148',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'df29c8df-9d25-40ec-a972-766e8b52041a',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 147,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3160,
        percentInventoryAvailable: 0.15,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022572,
        name: 'Billie Eilish',
        venueId: 2202,
        venueConfigurationId: 62325,
        eventTimeLocal: '2025-10-25T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022699,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-25T23:00:00',
        eventPerformers: [
          {
            id: 1208332,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2202,
          name: 'UBS Arena',
          city: 'Elmont',
          state: 'NY',
          postalCode: '11003',
          country: 'US',
          latitude: 40.71179,
          longitude: -73.72604,
          capacity: 1900,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 9,
          slug: 'ubs-arena',
          popularity: 1,
          singleLineAddress: 'Elmont, NY 11003',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'f96bab4c-e080-4274-80cd-fe66c262621f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 149,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 2814,
        percentInventoryAvailable: 1.48,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022577,
        name: 'Billie Eilish',
        venueId: 2202,
        venueConfigurationId: 62325,
        eventTimeLocal: '2025-10-26T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022700,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-10-26T23:00:00',
        eventPerformers: [
          {
            id: 1208337,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 2202,
          name: 'UBS Arena',
          city: 'Elmont',
          state: 'NY',
          postalCode: '11003',
          country: 'US',
          latitude: 40.71179,
          longitude: -73.72604,
          capacity: 1900,
          timeZone: 'America/New_York',
          parentVenue: false,
          parking: false,
          regionId: 9,
          slug: 'ubs-arena',
          popularity: 1,
          singleLineAddress: 'Elmont, NY 11003',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'f96bab4c-e080-4274-80cd-fe66c262621f',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T12:00:00',
        lastPresaleTimeLocal: '2025-05-22T12:00:00',
        firstOnSaleTimeLocal: '2025-05-22T12:00:00',
        daysToEvent: 150,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3335,
        percentInventoryAvailable: 1.76,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022580,
        name: 'Billie Eilish',
        venueId: 1718,
        venueConfigurationId: 62327,
        eventTimeLocal: '2025-11-07T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022721,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-08T01:00:00',
        eventPerformers: [
          {
            id: 1208340,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1718,
          name: 'Smoothie King Center',
          city: 'New Orleans',
          state: 'LA',
          postalCode: '70113',
          country: 'US',
          latitude: 29.94904,
          longitude: -90.08206,
          capacity: 17791,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 5,
          slug: 'smoothie-king-center',
          heroImagePath: 'https://static.gotickets.com/6650e7fe-7522-4554-84f7-071c6bcadef8.webp',
          popularity: 1,
          singleLineAddress: 'New Orleans, LA 70113',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'b0cbc098-f266-4766-b9d7-e24f4e30bc9b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 162,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3969,
        percentInventoryAvailable: 0.22,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022581,
        name: 'Billie Eilish',
        venueId: 1718,
        venueConfigurationId: 62327,
        eventTimeLocal: '2025-11-08T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022722,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-09T01:00:00',
        eventPerformers: [
          {
            id: 1208342,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1718,
          name: 'Smoothie King Center',
          city: 'New Orleans',
          state: 'LA',
          postalCode: '70113',
          country: 'US',
          latitude: 29.94904,
          longitude: -90.08206,
          capacity: 17791,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 5,
          slug: 'smoothie-king-center',
          heroImagePath: 'https://static.gotickets.com/6650e7fe-7522-4554-84f7-071c6bcadef8.webp',
          popularity: 1,
          singleLineAddress: 'New Orleans, LA 70113',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'b0cbc098-f266-4766-b9d7-e24f4e30bc9b',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 163,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3580,
        percentInventoryAvailable: 0.2,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022601,
        name: 'Billie Eilish',
        venueId: 323,
        venueConfigurationId: 62341,
        eventTimeLocal: '2025-11-10T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1025270,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-11T01:00:00',
        eventPerformers: [
          {
            id: 1208364,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 323,
          name: 'BOK Center',
          city: 'Tulsa',
          state: 'OK',
          postalCode: '74103',
          country: 'US',
          latitude: 36.15274,
          longitude: -95.99636,
          capacity: 19199,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 53,
          slug: 'bok-center',
          heroImagePath: 'https://static.gotickets.com/b8dafdf1-b35d-40b6-8177-c00102179a52.webp',
          popularity: 2,
          singleLineAddress: 'Tulsa, OK 74103',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '0c3443bd-4b52-4247-95b2-4f0ad92e71bb',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 165,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 2586,
        percentInventoryAvailable: 0.13,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022589,
        name: 'Billie Eilish',
        venueId: 323,
        venueConfigurationId: 62341,
        eventTimeLocal: '2025-11-11T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022588,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-12T01:00:00',
        eventPerformers: [
          {
            id: 1208350,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 323,
          name: 'BOK Center',
          city: 'Tulsa',
          state: 'OK',
          postalCode: '74103',
          country: 'US',
          latitude: 36.15274,
          longitude: -95.99636,
          capacity: 19199,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 53,
          slug: 'bok-center',
          heroImagePath: 'https://static.gotickets.com/b8dafdf1-b35d-40b6-8177-c00102179a52.webp',
          popularity: 2,
          singleLineAddress: 'Tulsa, OK 74103',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '0c3443bd-4b52-4247-95b2-4f0ad92e71bb',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 166,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3089,
        percentInventoryAvailable: 0.16,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022591,
        name: 'Billie Eilish',
        venueId: 1305,
        venueConfigurationId: 62328,
        eventTimeLocal: '2025-11-13T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022590,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-14T01:00:00',
        eventPerformers: [
          {
            id: 1208352,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1305,
          name: 'Moody Center ATX',
          city: 'Austin',
          state: 'TX',
          postalCode: '78712',
          country: 'US',
          latitude: 30.28097,
          longitude: -97.73066,
          capacity: 15000,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 28,
          slug: 'moody-center-atx',
          heroImagePath: 'https://static.gotickets.com/7e2d804d-5b01-4b29-b9d7-86bee86c4a7c.webp',
          popularity: 1,
          singleLineAddress: 'Austin, TX 78712',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'cca8148c-2741-46e0-8d1f-9eaadefd9d70',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 168,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 2834,
        percentInventoryAvailable: 0.19,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022594,
        name: 'Billie Eilish',
        venueId: 1305,
        venueConfigurationId: 62328,
        eventTimeLocal: '2025-11-14T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022728,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-15T01:00:00',
        eventPerformers: [
          {
            id: 1208355,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 1305,
          name: 'Moody Center ATX',
          city: 'Austin',
          state: 'TX',
          postalCode: '78712',
          country: 'US',
          latitude: 30.28097,
          longitude: -97.73066,
          capacity: 15000,
          timeZone: 'America/Chicago',
          parentVenue: false,
          parking: false,
          regionId: 28,
          slug: 'moody-center-atx',
          heroImagePath: 'https://static.gotickets.com/7e2d804d-5b01-4b29-b9d7-86bee86c4a7c.webp',
          popularity: 1,
          singleLineAddress: 'Austin, TX 78712',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'cca8148c-2741-46e0-8d1f-9eaadefd9d70',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T13:00:00',
        lastPresaleTimeLocal: '2025-05-22T13:00:00',
        firstOnSaleTimeLocal: '2025-05-22T13:00:00',
        daysToEvent: 169,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 2328,
        percentInventoryAvailable: 0.16,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022596,
        name: 'Billie Eilish',
        venueId: 14,
        venueConfigurationId: 62329,
        eventTimeLocal: '2025-11-18T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1025379,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-19T02:00:00',
        eventPerformers: [
          {
            id: 1208357,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 14,
          name: 'PHX Arena',
          city: 'Phoenix',
          state: 'AZ',
          postalCode: '85004',
          country: 'US',
          latitude: 33.44574,
          longitude: -112.0712,
          capacity: 18422,
          timeZone: 'America/Phoenix',
          parentVenue: false,
          parking: false,
          regionId: 12,
          slug: 'phx-arena',
          heroImagePath: 'https://static.gotickets.com/9f8b8158-538a-4f87-ada3-2c194414b450.webp',
          popularity: 1,
          singleLineAddress: 'Phoenix, AZ 85004',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '30b303fe-6a1d-42dd-97a3-469f7a20df5c',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T15:00:00',
        lastPresaleTimeLocal: '2025-05-22T15:00:00',
        firstOnSaleTimeLocal: '2025-05-22T15:00:00',
        daysToEvent: 173,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3232,
        percentInventoryAvailable: 0.18,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022593,
        name: 'Billie Eilish',
        venueId: 14,
        venueConfigurationId: 62329,
        eventTimeLocal: '2025-11-19T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022592,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-20T02:00:00',
        eventPerformers: [
          {
            id: 1208354,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 14,
          name: 'PHX Arena',
          city: 'Phoenix',
          state: 'AZ',
          postalCode: '85004',
          country: 'US',
          latitude: 33.44574,
          longitude: -112.0712,
          capacity: 18422,
          timeZone: 'America/Phoenix',
          parentVenue: false,
          parking: false,
          regionId: 12,
          slug: 'phx-arena',
          heroImagePath: 'https://static.gotickets.com/9f8b8158-538a-4f87-ada3-2c194414b450.webp',
          popularity: 1,
          singleLineAddress: 'Phoenix, AZ 85004',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: '30b303fe-6a1d-42dd-97a3-469f7a20df5c',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T15:00:00',
        lastPresaleTimeLocal: '2025-05-22T15:00:00',
        firstOnSaleTimeLocal: '2025-05-22T15:00:00',
        daysToEvent: 174,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3562,
        percentInventoryAvailable: 0.19,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022583,
        name: 'Billie Eilish',
        venueId: 472,
        venueConfigurationId: 62323,
        eventTimeLocal: '2025-11-22T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022582,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-23T03:00:00',
        eventPerformers: [
          {
            id: 1208344,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 472,
          name: 'Chase Center',
          city: 'San Francisco',
          state: 'CA',
          postalCode: '94158',
          country: 'US',
          latitude: 37.76802,
          longitude: -122.38788,
          capacity: 19500,
          timeZone: 'America/Los_Angeles',
          parentVenue: false,
          parking: false,
          regionId: 17,
          slug: 'chase-center',
          heroImagePath: 'https://static.gotickets.com/ca1f56ec-cf1b-419e-8107-f36ae81ff6fc.webp',
          popularity: 1,
          singleLineAddress: 'San Francisco, CA 94158',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'd5781a28-a873-469e-b479-731029cb0599',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T15:00:00',
        lastPresaleTimeLocal: '2025-05-22T15:00:00',
        firstOnSaleTimeLocal: '2025-05-22T15:00:00',
        daysToEvent: 177,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3991,
        percentInventoryAvailable: 0.2,
      },
      {
        doc: 0,
        fields: 0,
        id: 1022575,
        name: 'Billie Eilish',
        venueId: 472,
        venueConfigurationId: 62323,
        eventTimeLocal: '2025-11-23T19:00:00',
        timeTbd: false,
        dateTbd: false,
        parking: false,
        parkingEventId: 1022574,
        ifNecessary: false,
        multiDate: false,
        eventTimeUtc: '2025-11-24T03:00:00',
        eventPerformers: [
          {
            id: 1208335,
            performerId: 8077,
            master: true,
            performer: {
              id: 8077,
              name: 'Billie Eilish',
              primaryCategoryId: 141,
              parking: false,
              slug: 'billie-eilish',
              heroImagePath:
                'https://static.gotickets.com/838715df-f0e2-4680-a67b-e59a417da126.webp',
              primaryCategory: {
                id: 141,
                name: 'Pop',
                parentId: 6,
                eventType: 'CONCERTS',
              },
              cmsPageId: 1052,
            },
          },
        ],
        venue: {
          id: 472,
          name: 'Chase Center',
          city: 'San Francisco',
          state: 'CA',
          postalCode: '94158',
          country: 'US',
          latitude: 37.76802,
          longitude: -122.38788,
          capacity: 19500,
          timeZone: 'America/Los_Angeles',
          parentVenue: false,
          parking: false,
          regionId: 17,
          slug: 'chase-center',
          heroImagePath: 'https://static.gotickets.com/ca1f56ec-cf1b-419e-8107-f36ae81ff6fc.webp',
          popularity: 1,
          singleLineAddress: 'San Francisco, CA 94158',
        },
        venueConfiguration: {
          name: 'UNIQUE Concert: Center stage + Floor + VIP Package (Billie Eilish)',
          svgMapFileName: 'd5781a28-a873-469e-b479-731029cb0599',
          generalAdmission: false,
          staticMap: false,
        },
        seasonTicket: false,
        lastOnsaleTimeLocal: '2025-05-22T15:00:00',
        lastPresaleTimeLocal: '2025-05-22T15:00:00',
        firstOnSaleTimeLocal: '2025-05-22T15:00:00',
        daysToEvent: 178,
        daysToOnsale: -6,
        daysToPresale: -6,
        daysUntilFirstOnSale: -6,
        pricingType: 'ALL_IN_TICKET_PAGE',
        availableTickets: 3727,
        percentInventoryAvailable: 0.19,
      },
    ],
    customFieldValues: {
      seoContentConcerts:
        '<div data-scroll-anchor="true" data-testid="conversation-turn-19" dir="auto">\n<div>\n<div dir="auto" data-message-id="970942cb-4d76-4259-b1c0-a06923df2c8b" data-message-author-role="assistant">\n<h2>Billie Eilish Tickets From GoTickets.com</h2>\n<p>Get ready to immerse yourself in the captivating world of Billie Eilish! When you secure your Billie Eilish tickets at GoTickets.com, you\'ll enjoy the benefits of our quick and seamless sales process and secure transactions. We designed our process to make purchases stress-free. Plus, with our 100% buyer guarantee, you can complete your transaction with confidence. Don\'t miss out on the show of a lifetime&mdash;buy your Billie Eilish tickets today!</p>\n<h2>About Billie Eilish</h2>\n<p>Billie Eilish, the teenage sensation turned global icon, has taken the music world by storm with her unique sound and unapologetic style. Born and raised in Los Angeles, California, Eilish began writing and producing music at a young age, crafting songs that reflect her introspective nature and eclectic influences. Her breakthrough came with the release of her debut single "Ocean Eyes" in 2016, which quickly went viral and catapulted her into the spotlight.</p>\n<p>Since then, Billie Eilish has become a household name, earning critical acclaim and a devoted fan base with her genre-defying music. Her debut album, <em>When We All Fall Asleep, Where Do We Go?</em>, solidified her status as a trailblazer in the industry, featuring chart-topping hits like "Bad Guy" and "Bury a Friend." Eilish\'s dark, atmospheric sound and thought-provoking lyrics have resonated with audiences worldwide, earning her multiple Grammy Awards and countless accolades.</p>\n<h2>What to Expect at a Billie Eilish Concert</h2>\n<p>At a Billie Eilish concert, fans can expect an immersive experience filled with mesmerizing visuals and spellbinding performances. Eilish\'s setlist features a mix of her biggest hits and deep cuts, showcasing the depth and versatility of her artistry. From the haunting melodies of "When the Party\'s Over" to the infectious energy of "You Should See Me in a Crown," each song takes audiences on a journey through Eilish\'s vivid imagination.</p>\n<p>One of the highlights of a Billie Eilish concert is the sense of connection between the artist and her fans, who share a deep appreciation for her music and message. Whether she\'s sharing personal anecdotes or interacting with the crowd, Eilish creates an intimate atmosphere that makes every concert feel like a shared experience. With her mesmerizing stage presence and powerful voice, Billie Eilish delivers a performance that is both electrifying and unforgettable.</p>\n<h2>Don\'t Miss Out!</h2>\n<p>Don\'t wait another moment to secure your Billie Eilish tickets from GoTickets.com. Explore our listings from trusted sellers and find the perfect seats so you don\'t miss out on the opportunity to witness this brilliant artist live on stage. Reserve your access now, and prepare to be swept away by her enchanting vocals at a venue near you!</p>\n</div>\n</div>\n<div></div>\n</div>',
    },
    redirect: false,
    eventSearchParameters: {
      performerId: [8077],
    },
    showScarcity: false,
  },
  response: {},
};
